sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ghostetler/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI-true ghostetler/docker-react npm run test